-- MySQL Script generated by MySQL Workbench
-- Sun Jan  9 02:27:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Contas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `saldo` FLOAT NOT NULL,
  `tipo_conta` smallint NOT NULL,
  `instituicao_financeira` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Despesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb.Despesas`;

CREATE TABLE IF NOT EXISTS `mydb`.`Despesas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `data_pag` DATE NOT NULL,
  `data_pag_esp` DATE NOT NULL,
  `tipo_despesa` smallint NOT NULL,
  `conta` varchar(50),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Receitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Receitas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `data_rec` DATE NOT NULL,
  `data_rec_esp` DATE NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  `tipo_receita` smallint NOT NULL,
  `conta` varchar(50),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

show tables
